name: cellxgene-gateway
channels:
- conda-forge
dependencies:
- python=3.9
- requests
- flask
- psutil
- black
- typer
- twine
- isort
- coverage
- pip
- pip:
  - pre_commit
  - flask-api
  - werkzeug
  - cellxgene
  - prometheus-flask-exporter
