name: cellxgene-gateway
channels:
- conda-forge
dependencies:
- python=3.9
- requests
- flask==2.2.5
- psutil
- black
- twine
- isort
- coverage
- pip
- pip:
  - pre_commit
  - flask-api
  - werkzeug==2.3.8
  - cellxgene
